### ISSUE TITLE
Better names for Game Types

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#105]
Right now in Lobby the Game Types are listed as *New Attack Style* and *VANILLA*. Neither of them really describe what the difference is.

**Comment by Phrancis** [comment]
@all - Do you think we should just drop VANILLA altogether and just stick to "New Attack Style"? I haven't played vanilla since like 0.2 I think, New Attack Style is more interesting IMO.

**Comment by Zomis** [comment]
Agreed. VANILLA is too easy, you just need to have a creature with a lot of health and the problem is solved.
