### ISSUE TITLE
Specify all possible events the core can generate

### ISSUE THREAD

**Issue by skiwi2** [Cardshifter/Cardshifter#12]
Our core will be able to generate a lot of events, all of which need to be actable upon.
We are talking about events like this:
 - Turn Start
 - On Action (right before a card gets played)
 - Turn End

There needs to be a system such that cards can add and remove event listeners on certain events.
You could have a real powerful card that has a chance to make you discard your whole hand when your turn starts. Upon activating that card, you need to be able to add that listener to the Turn Start method. When the card is deactivated, the listener needs to be removed.

We need a list of all possible events, generated by the core, on which can be acted upon.

**Comment by Zomis** [comment]
Is this something that @Phrancis could work on for the website? I could help with the descriptions of the events, of course.

**Comment by Phrancis** [comment]
I'm down, not exactly sure what you are looking for though...?

**Comment by Zomis** [comment]
I'm thinking that in the "Make your own mod" section, these things could be stated, that the events are the main way mods interact with the game when it is being run. Then follows a list of all the events with a description of when they're being executed.

**Comment by Phrancis** [comment]
I think we got this one largely handled now that we switched to Groovy. I have documented all of those that I know will be in 0.6 and we can update the modding documentation as we add new things in the future.
