### ISSUE TITLE
Add image/logo to the Cardshifter repos

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#145]
Need to get a finished logo or image for the repositories. This will show under "Author" in SEO when people search for our project.

**Comment by Zomis** [comment]
@Phrancis is this something you are working on now?

**Comment by Phrancis** [comment]
Yeah this is basically the same thing as [#35](https://github.com/Cardshifter/cardshifter.github.io/issues/35) on the io repo.
