### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#149]
This project really ***needs*** a specific license. It is about time to pick one, @Phrancis @bazola @skiwi2 .

Personally, I'd like to see an open license such as Apache License version 2, or BSD License, or MIT. Whichever way we go, this needs to be decided.

**Comment by Phrancis** [comment]
I read about all 3 licenses, my personal pick would be Apache 2.0, although MIT seems pretty similar, if only a bit less widespread. BSD seems intended more towards commercial software where one may have competitors, which I don't believe is the case as far as Cardshifter is concerned/intended.

**Comment by Zomis** [comment]
Input wanted from @skiwi2 and @bazola

**Comment by Vogel612** [comment]
I personally find the MIT license to be not  restrictive enough (especially concerning copyleft clause and attribution). IMO picking MIT is somewhat equivalent to dedicating things to public domain (also known as: CC0). I think that's not quite the plan here, so I'd advise against MIT ;)

**Comment by Phrancis** [comment]
Quick question, will cardshifter.github.io website repo have to share the same license? If so, does the license only apply to the code? 

I'm mostly concerned thinking of some future scenario where we will have media content (e.g., images for cards and such) present in both the game and the site, though they are not code.

**Comment by Zomis** [comment]
the website repository can absolutely have a different license, and media content can also be licensed differently.

**Comment by Zomis** [comment]
Can @bazola please comment on this?

**Comment by bazola** [comment]
I'm no expert, but I think that Apache 2.0 is the best fit overall.

**Comment by Zomis** [comment]
Does, @skiwi2 agree?

**Comment by skiwi2** [comment]
I think the Apache 2.0 is fine, I see no concrete reasons to not use it, but I'm not an expert either.
