### ISSUE TITLE
GWT support

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#154]
Currently, we're not supporting gwt - which means we can't export as HTML5 application. If we make the following changes, we could:

- Remove log4j dependency in cardshifter-api, or possibly try http://log4j-gwt.sourceforge.net/
- Remove jackson dependency in cardshifter-api, use jackson mixins instead, or possibly write the code in such a way that jackson annotations are not required

**Comment by Zomis** [comment]
Networking in GWT + LibGDX also has to be done in a special way, using Websockets.

**Comment by Phrancis** [comment]
I think with the development of the [HTML-Client](https://github.com/Cardshifter/HTML-Client) we no longer need to concern ourselves about supporting GWT at all now.
