### ISSUE TITLE
Wiki landing page is very bare

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#158]
The landing page currently only says "Welcome to the Cardshifter wiki!". I think it would be advantageous to at least have a brief guidance on what each section is for. Also wouldn't hurt to make a custom footer, and side bar perhaps with links to external sources like Waffle and such.

**Comment by Zomis** [comment]
I don't believe you can add a side bar to the wiki. All wiki pages are simple .md files, meaning that they only support markdown.

**Comment by Phrancis** [comment]
Added side bar with external links (same as in the chat room) and footer with a Contact Us link (that will redirect to that section on the website)

**Comment by Phrancis** [comment]
Wiki Home page has been updated with overview of the different sections.
