### ISSUE TITLE
Saving card abilities in files

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#164]
Have the possibility to more easily (i.e. without coding) modify card abilities, such as "ranged", "heal 1 at end of turn", "summon 2 xx creatures when played". Modify these by using some human readable file format, such as XML, JSON, or make our own.

It could be possible to declare some abilities in an ability file.

Some examples of possible ability files:

### ranged.ability (Custom format)

    setResource( DENY_COUNTERATTACK, 1 )

### ranged.ability (XML)

    <ability type="resource">
          <parameter>DENY_COUNTERATTACK</parameter>
          <parameter>1</parameter>
    </ability>

### summon-2-BodyMan.ability (XML)

    <ability type="EffectComponent">
    <parameter method="Effects.toSelf">
         <parameter method="Effects.toPlayer">
               <parameter method="Effects.summon">
                      <parameter>2</parameter>
                      <parameter>Body Man</parameter>
               </parameter>
        </parameter>
    </parameter>
    </ability>

See http://www2.zomis.net/tcg-creation/132/alternatives-for-storing-cards?show=167#a167

**Comment by Zomis** [comment]
Another option that has emerged recently is to use JSON-like structure within JS:

http://chat.stackexchange.com/transcript/message/21374847#21374847
http://chat.stackexchange.com/transcript/message/21375057#21375057

**Comment by Phrancis** [comment]
Referencing #199

**Comment by Zomis** [comment]
Implemented with #180

**Comment by Zomis** [comment]
Even better implemented with #222
