### ISSUE TITLE
How do I build your latest release?

### ISSUE THREAD

**Issue by ckuhn203** [Cardshifter/Cardshifter#168]
I can't find any information on how to build the project, either from the release or current branches?
How do I build /or run the game?

**Comment by Zomis** [comment]
There are downloadable versions here: https://github.com/Cardshifter/Cardshifter/releases
There is no need to build from sources.
There is also instructions for "Playing the game" on our readme: https://github.com/Cardshifter/Cardshifter

Please let us know if the documentation can be approved for this!

**Comment by Phrancis** [comment]
@ckuhn203 There is also an instructions page on (yet to be published) Cardshifter website, if you can read between the HTML tag it's all here: https://github.com/Cardshifter/cardshifter.github.io/blob/master/io.web/src/main/webapp/WEB-INF/play-cardshifter.html

**Comment by Zomis** [comment]
@Phrancis @ckuhn203 It is actually published, but here: http://stats.zomis.net/io-web/play-cardshifter

**Comment by ckuhn203** [comment]
Thank you! @Zomis  you may want to consider linking back to [this page][1] from the [release notes][2].
The would drastically reduce confusion for people like me who found the repo before the website.

[1]:http://stats.zomis.net/io-web/play-cardshifter
[2]:https://github.com/Cardshifter/Cardshifter/releases

**Comment by Zomis** [comment]
@Phrancis Will add a wiki page in the repository that I can link to in the release notes.

**Comment by Phrancis** [comment]
@Zomis Here is a link to the new page: https://github.com/Cardshifter/Cardshifter/wiki/How-to-play-Cardshifter

Would you please proof it, make any edits you feel are needed, and add link to the releases page?
