### ISSUE TITLE
Creatures with Ranged - too powerful?

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#171]
Currently a good strategy might be to get a lot of minions with Ranged out as early as possible, if you manage to do that then they are invulnerable unless your opponent has creatures with Rush.

Should the Ranged ability be nerfed somehow? Or deleted altogether?

**Comment by Phrancis** [comment]
I have noticed they are quite good indeed, although in general you will notice I have made the cards with Ranged have a quite low health. Perhaps increasing their cost slightly would mitigate early-game Ranged domination? I don't think it should be deleted though.

**Comment by Phrancis** [comment]
On a side note, once we introduce spells and counters and such, the Ranged advantage could change drastically. We could also impose a lower limit to cards with Ranged, say 1 of each instead of 3.

**Comment by Zomis** [comment]
I think imposing a lower limit on the cards is a good option for it. Increasing the mana cost is definitely good. I was also thinking about a drawback on them such as "This card can only attack each 2nd turn", what do you think about that one?

**Comment by Phrancis** [comment]
I actually like that a lot! So in essence it would cast Sickness on the card on any turn after it attacks? Even within the setting it makes sense, for a sniper or cannon or whatever to have to reload after a powerful shot.

**Comment by Zomis** [comment]
I don't know if I will re-use the Sickness property for it, but essentially it will work that way, yes :)
