### ISSUE TITLE
Game does not come with any decks

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#172]
I think it would be a good feature for someone to be able to just have the deck builder build a deck with random cards. Example:
- For beginners who just want to learn the ropes
- For quick testing
- For fun/challenge for more experienced players

I suggest perhaps a button like "Feeling lucky?" or just "Randomize" in the deck builder.

**Comment by Zomis** [comment]
There are a few variants here:

- Complete randomness. This *can* lead to a deck with very many enchantments but very, or even none, few mechs to scrap or bios to use them on.
- Randomness with limits. Use randomness, but make sure that a certain amount of Mechs, Bios and Enchantments are picked. Remember that this variant needs to be extensible and moddable, not coded into the clients.
- Pre-built "Beginner" deck.

**Comment by Phrancis** [comment]
Good points. I think a Beginner deck would be simplest, but Randomness with limits would be most useful. Complete Random I guess is probably not a very good choice

**Comment by Phrancis** [comment]
@Zomis could we put in for next release to have a few `*.deck files` packaged in with the rest of the files? I can make the decks themselves and provide the files (maybe in `extra-resources`?). This would be better than nothing until we talk more about randomizing decks.

**Comment by Phrancis** [comment]
In fact, the more I think about randomizing decks, the more I think YAGNI and just packaging a few starter decks with the game would perfectly satisfy UX for new players trying the game. I'll rename the issue appropriately.

**Comment by Zomis** [comment]
I agree that starter decks is better than randomizing decks. You could put them in a directory as follows: `extra-resources/decks/Cyborg-Chronicles` and I think that should then work.

**Comment by Phrancis** [comment]
This was already taken care of, just forgot to close it
