### ISSUE TITLE
All cards not showing in deck builder

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#173]
Per attached screenshot (showing page 2 of cards library) the bottom menu bar overlaps the cards. A vertical scroll or other navigation mechanism to see cards that are on the 3rd row or below would be needed to see all cards on any given page. 

![deck-builder-bug](https://cloud.githubusercontent.com/assets/8539648/6204049/495a561a-b50a-11e4-8d67-636efb265f89.png)

**Comment by Zomis** [comment]
I think this can also be helped by only showing 10 cards on each page.

**Comment by Phrancis** [comment]
That would work too, let me edit the title to be more relevant

**Comment by Phrancis** [comment]
Actually I don't think limiting to 10 cards displayed per page would fix this. I attached a screenshot to that effect, which does indeed show only 10 cards, but the length of the names "push" the 10th card down to the next row.

The problem seems to be caused by the "Prev / Next" bar floating on top of the card display page. If it were possible to move it somewhere else (perhaps snap it to the top above the cards page, or to the bottom below it) I think that would be a better fix. 

![image](https://cloud.githubusercontent.com/assets/8539648/6431482/249048bc-bfff-11e4-9734-18d76c1ff5a0.png)

**Comment by Zomis** [comment]
The real problem is that the cards are bigger than they should be allowed to be. There should be a max width for all the labels of the card, and/or for the card itself.

**Comment by Phrancis** [comment]
This can wait for 0.7 - Also related #250
