### ISSUE TITLE
Prevent being able to invite yourself to a game

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#174]
From the lobby I clicked my own name and invited myself to a game, which did send me an invite request, then brought up the deck builder twice, and then once I Start Game is just stays there and does nothing. I think an error message from the lobby would be more appropriate when trying to invite yourself to a game. 
![self-invite](https://cloud.githubusercontent.com/assets/8539648/6205631/eec4f942-b542-11e4-8d3c-0fe36d123a8c.png)

**Comment by Phrancis** [comment]
This might be better fit for 0.7?

**Comment by Zomis** [comment]
I think this can be fixed on the server-side and it shouldn't be too hard so I think 0.6 is reasonable for this.
