### ISSUE TITLE
The Entity to which a Component is attached is not reset when removing a component from an entity

### ISSUE THREAD

**Issue by skiwi2** [Cardshifter/Cardshifter#179]
When you remove a component from an `Entity`, then the component stays attached to the `Entity`.
This prevents you from adding that component to another entity.

Observe in https://github.com/Cardshifter/Cardshifter/blob/develop/cardshifter-modapi/src/main/java/com/cardshifter/modapi/base/Entity.java the following code:
```
public Entity addComponent(Component component) {
    components.put(component.getClass(), component);
    component.setEntity(this);
    return this;
}
```

And the following:
```
public void removeComponent(Class<? extends Component> component) {
    this.components.remove(component);
}
```

In the `removeComponent` a `component.setEntity(null)` call should be made.

**Comment by Zomis** [comment]
Agreed, it is a bug. But note that normally, you're not really expected to add and remove *the same component* on an entity. After removing a component, it would make more sense to add a new component.

**Comment by Zomis** [comment]
Not that I really expect it to be used much, but this has now been fixed.
