### ISSUE TITLE
Modding with Nashhorn JavaScript Engine

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#180]
Inspired by @skiwi2's recent [question on Code Review](http://codereview.stackexchange.com/q/82399/31562), it seems like Cardshifter could benefit from having a possibility to create mods in JavaScript.

Ideally, it should be possible to make more or less *all* the modding through JavaScript, not only defining the cards and loading them from Java (as is currently possible). The core mod itself and the cards should be able to keep in separate files, for Separation Of Concerns.

**Comment by Phrancis** [comment]
I think this is obsolete now that we're using Groovy.

**Comment by Zomis** [comment]
yup, I will definitely not continue working on the JS modding aspect, but I think the possibility to use JS should remain.

**Comment by Zomis** [comment]
"the possibility to use JS should remain"? Pffft! Just want to say that that ain't gonna happen.
