### ISSUE TITLE
Card effects apply while present

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#182]
@MGS1GreyFox and I have been discussing this possibility to have a creature that, while it is present, applies certain effects on other creatures. A simple example would be "Add 1 health to other creatures while present". I would picture along the lines of `apply:whilePresent:addHealth:1`.

A slightly more advanced application would involve a creature's type, for example: `apply:whilePresent:addAttack:1:"Mech"` to raise Mechs' attack by 1. 

Another possible application, perhaps for later, would be something that targets the opponents creatures, which may be more flexible if we used "change" logic instead of "add/subtract" if possible.  `apply:whilePresent:changeAttack:-1:opponent:"Bio"` though there probably is a simpler way of doing it that I'm unaware of (besides stringing a whole bunch of arguments together).

The most important property of this would have to be that the effect applies when, and only when the creature is present in play. For instance:
- When the creature is cast, the effect applies immediately, not on end of turn or start of next turn. 
- When the creature is destroyed, the effect stops applying immediately. 

I think this kind of mechanics is something modders would be looking for and we should make a way to support it.

**Comment by Zomis** [comment]
Yup, this is indeed something that is required and it is something that is possible to accomplish with the Java system using some tricks. Could you come up with a bunch of cards that could have this kind of effect? (It is much easier to implement if there is a concrete goal)

You can also take inspiration [from this Q&A question](http://www2.zomis.net/tcg-creation/137/new-ability-and-spell-ideas?show=137#q137). Anything is possible!

**Comment by Phrancis** [comment]
I just now realized you asked me to do something on this one, my bad. I'll come up with stuff over the weekend. If you can give me a "name" or format to use I can even add them in the cardload branch

**Comment by Zomis** [comment]
There is no name or format to use at the moment. Plain English will be the best.

**Comment by Phrancis** [comment]
Here are a few simple examples, hopefully can be implemented to use any value.
- [ ] While present add _n_ health to own Mech creatures
- [ ] While present add _n_ health to own Bio creatures
- [ ] While present add _n_ health to all own creatures
- [ ] While present add _n_ attack to own Mech creatures
- [ ] While present add _n_ attack to own Bio creatures
- [ ] While present add _n_ attack to all own creatures
- [ ] While present subtract _n_ attack to opponent Mech creatures
- [ ] While present subtract _n_ attack to opponent Bio creatures
- [ ] While present subtract _n_ attack to all opponent creatures

I'm not if sure reducing opponent creatures' health would be good (as it might kill them as soon as they are cast) unless it could not be reduced below one by this effect. Thoughts?

**Comment by Zomis** [comment]
yeah, all those different requests is essentially one and the same:

While present add/subtract n attack/health to (creatures)

**Comment by Zomis** [comment]
This has now been implemented, but see #206 and #210 for some related missing features (or bugs)
