### ISSUE TITLE
JSON card loader with effects

### ISSUE THREAD

**Issue by skiwi2** [Cardshifter/Cardshifter#183]
A card loader should be implemented that can load cards together with its effects in a JSON format.

An example of a card object could be the following:
```
{
	name: "Ragnaros",
	attack: 8,
	hitpoints: 8,
	keyword: [kwCantAttack],
	onEndOfTurn: function(game) {
		game.opponent().characters().pickRandom(1).dealDamage(8);
	}
}
```

The following parts should be satisfied by this card loader:
 - You can supply a resources list, and it should load those resources if defined in the object.
 - You can supply an attributes list, and it should load those attributes if defined in the object.
 - You should be able to hook functions on all possible phases.
 - It should be possible to transform keywords, for example `keyword: [kwCantAttack]` rather than `kwCantAttack: 1`, also `deathrattle` versus `onEntityDeath`.
 - You should be able to provide a "Domain Specific Language" Java class that has static methods that make it possible to use `opponent()`, `characters()`, `pickRandom(1)`, `dealDamage(8)`, etc.

Closely related to https://github.com/Cardshifter/Cardshifter/issues/131.

**Comment by Zomis** [comment]
Closely related? I'd more say "duplicate".

**Comment by Zomis** [comment]
@skiwi2 Is it just me or has this been implemented with the new js-load branch and JS modding system?

**Comment by skiwi2** [comment]
It's (correct me if wrong) using a different approach, but the goal is quite similar indeed.

**Comment by Zomis** [comment]
I'd say that is correct, yes. It's up to you whether or not you want to continue working on this one. I'll remove the "in progress" label as there haven't been any news on this one for a while.

**Comment by Zomis** [comment]
I don't think this is going to happen, considering what the new Groovy modding has showed. Closing this as wontfix.
