### ISSUE TITLE
Card data; what format to use?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#190]
There have been multiple options thrown around on how to store/load card data into a game instance. Currently, we're using a custom file format (`.cards`) file stored in extra resources directory. There's also the options of using a common data format, like JSON or XML. Whichever one we end up using, I think we need to settle on one format. 

With some of the game logic being moved to JavaScript, JSON seems like a natural choice. But, is it easy enough for an "outsider" (a modder, etc.) to use? Or is the current format better, from UX perspective? XML is also an option, being a very common data format no doubt JS could handle it well, but what about the core Java server?

**Comment by Zomis** [comment]
Core Java server can handle anything you throw in its way. It is the most flexible of them all.

Personally, I don't think XML is a good choice.

The main 'problem' about the data format is that it somehow needs to be able to define effects in it. The `.cards` format handles this by calling Java methods with reflection, which is not a very flexible approach. Although that cards format can be enhanced to support such features somehow, I think JSON might be the best option here.

I do not know from an "outsider" perspective though what the best is.

**Comment by Phrancis** [comment]
Referencing Issue #183

**Comment by Phrancis** [comment]
@Zomis Do you think JSON along with JS could be an effective way to define effects? Or do the effects necessarily need to remain in the Java core code?

**Comment by Zomis** [comment]
It should be possible to define effects externally, which is one big reason for why the JS branch exists. JSON and JS could be a solution to define these effects.

To be sure about that though, I think it is a good idea to come up with several example effects, both simple and advanced ones, and show how we would want them to be implemented with whatever format we go with.

**Comment by Phrancis** [comment]
Do you think it would be a good start to try to implement currently existing effects using another format? Or come up with something completely new?

**Comment by Zomis** [comment]
The current existing effects are quite simple. I think we pretty much only are using "At the end of your turn, heal 1 hp". Coming up with new effects and coming up with examples for how we would want those to look in JSON/JS format would be good.

**Comment by Phrancis** [comment]
After discussing at length in chat, we will try to get cards and effects going using JSON. For reference, read from here down: http://chat.stackexchange.com/transcript/message/21374847#21374847
