### ISSUE TITLE
Document ECSResourceMap behavior

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#198]
This should be valuable for modding. We should be able to follow from PhrancisGame.java out to find out what data is manipulated and how, as a game is played.

**Comment by Zomis** [comment]
What exactly is it that you want to document? Please elaborate.

**Comment by Phrancis** [comment]
I don't think this will be needed after all. I think your JS implementation looks good and won't need this particular type of documentation, at least for now.
