### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#200]
There are a bunch of code on the `master` and `develop` branches that we are not using at the moment. Clean this up.

Examples are the cardshifter-console code, and the `com.cardshifter.core.Game` class (and related code) which are related to the old Lua code. I'm sure though that there's more than this.

**Comment by Zomis** [comment]
There's a part of the JavaFX project that's not being used as well, that was refactored away a while ago (when the JavaFX code started to use the same view for both server-based and local-based games)

**Comment by Zomis** [comment]
Potential cleanup items:

- [ ] CyborgChronicles Java code
- [ ] JS modding
- [ ] JavaFX old client-sided code (and FXML files)
- [ ] Cardshifter-console project
- [ ] Old Lua code (from Cardshifter 0.2 pretty much...)
- [ ] Various card loaders
- [ ] Various mod loaders
- [ ] The Java Effects class, transform a lot to Groovy instead
- [ ] Unused mods (HS, CW2)
- [ ] Unused fights code `com.cardshifter.server.utils.fight`

**Comment by Zomis** [comment]
Decided to not remove the cardshifter-console project, it might still be useful... or something.

Anyway, I consider this issue finished for now, although it's probably just a matter of time before we need to clean up some more.

**Comment by jacwah** [comment]
I had to touch some cardshifter-console code today while removing an API message (see ae148a007d871a22b9075efbb5003bdb67893819). Keeping the module will cost us maintenance time, and I can't see any situation were keeping it would be useful. If we ever need part of the code it's readily available in the Git history.

I think the cardshifter-console module should be removed altogether.

**Comment by Zomis** [comment]
Agreed, please move cardshifter-console to `/dev/null`, @jacwah.

**Comment by jacwah** [comment]
I had to touch some cardshifter-console code today while removing an API message (see ae148a007d871a22b9075efbb5003bdb67893819). Keeping the module will cost us maintenance time, and I can't see any situation were keeping it would be useful. If we ever need part of the code it's readily available in the Git history.

I think the cardshifter-console module should be removed altogether.

**Comment by jacwah** [comment]
From ad904352a71307201a32e900231c69546a927b20:

[![asciicast](https://asciinema.org/a/eyp9ep5645tktciqyeocvz0hr.png)](https://asciinema.org/a/eyp9ep5645tktciqyeocvz0hr)

*Finally got to use that! :grin:*
