### ISSUE TITLE
Add "description" field to ECSAttributeMap

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#201]
This will be an optional field to be used to explain to the player, in short plain English, what the effects of the card are. This will be left empty if the card has no special effects. It can be identical to `ECSAttribute.FLAVOR` as far as I'm concerned, unless there is good reason to do it differently, of which I cannot think of.

**Comment by Zomis** [comment]
I'm not sure if this is required at the moment, as I have managed to dynamically generate the description?

**Comment by Phrancis** [comment]
I agree.
