### ISSUE TITLE
whilePresent, onEndOfTurn, and afterPlay at once

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#211]
It needs to be possible to have whilePresent, onEndOfTurn, and afterPlay at once on the same card, preferably also a combination of each.

For example:
All your creatures have +1/+1
All opponent creatures have -1/-1
At the beginning of your turn, draw a card.
At the beginning of each opponents turn, that player takes 1 damage.
When you play this, deal 2 damage to all enemy creatures.
When you play this, summon a card in your hand.

(How all this is supposed to fit on the client GUIs, I do not know, but in the code it should be possible)

**Comment by Phrancis** [comment]
Are there any "technical" obstacles with doing this? I can make a card that has all 3 and see if it works correctly if you like

**Comment by Zomis** [comment]
The core code needs to be modified slightly in order to support it.
