### ISSUE TITLE
Implement Spell-type cards

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#213]
Spell types that come to mind immediately would be things like: 
 - Deal n damage to card of type X 
 - Take n card(s) from opponent hand / draw pile / discard pile 
 - Restore n card(s) of type X from own discard pile 
 - Remove n / all enchantment(s) from card X

The idea is that once a spell is played and its effects have been applied, it immediately goes into the discard pile.

**Comment by Phrancis** [comment]
Related: Issue #212 and #102

**Comment by Phrancis** [comment]
Also another spell type that could be desirable, would be to cause damage directly to the player, regardless of them having units that can block creatures

**Comment by MGS1GreyFox** [comment]
I would also like to add a "mind control spell" take control of target creature until end of turn.
Also a "disenchant" that would take upgrades off of a target creature, if scrap and all of that is still being used. It's been a bit since we talked about that function. I will add more as I think of them!

**Comment by Phrancis** [comment]
Referencing a previous discussion about spells on the Q&A forum: http://www2.zomis.net/tcg-creation/137/new-ability-and-spell-ideas

**Comment by Zomis** [comment]
I got a feeling this will show up in Mythos mod? -- #223

**Comment by Phrancis** [comment]
Actually, I was more thinking of a strictly creature-based mod for Mythos. Spells would work better with the mana system in Cyborg Chronicles

**Comment by Zomis** [comment]
I got a feeling that Mythos might need some spells as well, but we'll see.

Either way, this will be supported in the Groovy modding

**Comment by Zomis** [comment]
This issue will be about being able to create spells in the Groovy DSL, and to target specific cards (such as 'Deal 3 damage to 2 target creatures'), for card effect suggestions please see #244

**Comment by Zomis** [comment]
Example spell:

    card('Cheating Arms') {
        spell {
            targets(min: 1) {
                creature true
                ownedBy 'you'
                zone 'Battlefield'
            }
        }
        afterPlay {
            damage 1 to targets
        }
    }

Other supported variants:

        spell {
            targets 4 cards {
                creature true
                ownedBy 'you'
                zone 'Battlefield'
            }
        }

And:

        spell {
            targets 2 to 4 cards {
                creature true
                ownedBy 'you'
                zone 'Battlefield'
            }
        }

**Comment by Zomis** [comment]
Another example, this time of a spell that does not require any targets:

    card('Rain') {
        spell()
        afterPlay {
            damage 1 to {
                zone 'Battlefield'
            }
        }
    }

This will deal 1 damage to all creatures on the battlefield.

**Comment by Zomis** [comment]
Another example:

    card('Fireball') {
        /* deal 1 damage to whatever target you choose */
        spell {
             targets 1 of {
                  zone 'Battlefield'
             }
        }
        afterPlay {
            damage 1 to targets
        }
    }
