### ISSUE TITLE
Refactor "PhrancisThings" to "CardshifterThings"

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#214]
I'm not a big fan of the "PhrancisThings" in the current code base, just because... Well, it's not my game, it's the Cardshifter game. It was good as a naming pattern for a good while, but I think a `PhrancisThing` should be refactored to a `CardshifterThing` throughout.

**Comment by Zomis** [comment]
Or even better: `CyborgChroniclesThing`, as that is the official name of that mod AFAIK.

**Comment by Phrancis** [comment]
That would work as well, since it looks like all the `PhrancisThings` are mod-related
