### ISSUE TITLE
Card images

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#217]
I think having actual graphics in the game will do a great deal to improve the "fun" factor. Aside from a few logos and such in the GUI, what steps do we need to take to actually support card images?

- Would the current JavaScript implementation be able to support this? For example, imagine a card like `{ name: "My Card", image: "my-card.png" }`
- What would be the best image format? Can we support multiple different image formats? I think supporting PNG and JPEG would be good, perhaps also GIF. I also know web-based languages support SVG (vectorial) graphics, but I think we've already established LibGDX does not support those at the time. 
- Can we realistically shoot for 0.7 for card images?

I think images would be a good incentive to attract potential modders, in addition to players.

**Comment by Phrancis** [comment]
Here are some test images in multiple formats, for testing/developing/reference

![test](https://cloud.githubusercontent.com/assets/8539648/7541099/9c9f0de6-f580-11e4-94ee-6e89da2dea9e.jpg)
![test](https://cloud.githubusercontent.com/assets/8539648/7541101/9cab2cb6-f580-11e4-8ba2-98406a90d43e.png)



![test](https://cloud.githubusercontent.com/assets/8539648/7541100/9ca13d8c-f580-11e4-9db3-139ce2f62293.gif)

**Comment by Zomis** [comment]
I think PNG is prio 1 to support. Then JPG. The hardest problem about this will be to have it moddable enough on the client side.

**Comment by Phrancis** [comment]
We are definitely going to need JPG for Mythos, I'm noticing that a lot of images of different deities on Wikimedia and such are largely JPG since they are renditions of traditional art

**Comment by Phrancis** [comment]
Looks like libGDX supports JPG and PNG both natively using `Texture` and `TextureRegion`. I think the trickier thing will be that AFAICT the images have to be stored locally in each of the libGDX data directories (one directory for each Handler) which means we will probably have to compress and manipulate images quite a bit so that the game is not too large of an application. For reference: https://github.com/libgdx/libgdx/wiki/Textures,-textureregion-and-spritebatch

I think a `TextureRegion` would likely be the most flexible, if we can map out even-size images then we can use the `split` convenience feature to cut out the images in the `TextureRegion` into an array, for example:

    TextureRegion[][] regions = TextureRegion.split(texture, 64, 64)

**Comment by Phrancis** [comment]
Alternatively, I think we could use individual images, and save the image path as an attribute in the Groovy DSL, then just inject that into libGDX where the images would be saved as assets. The tricky part would be that it would probably need to run code like this example, but get the paths from external data, for example an `ImagePath "mythos/card-images/Chinese/monking.png"`

    public void create() {
        cardTexture = new Texture(Gdx.files.internal("mythos/card-images/Chinese/monking.png"));
        batch = new SpriteBatch();
    }

This will need some research, I checked on StackOverflow and in the manual and it's unclear how this could be done.

**Comment by Zomis** [comment]
The data about which file to load could be sent to the client from the server. Technically, it could also be possible to download images as needed from the internet (we would need to host them ourselves then, of course).

**Comment by Phrancis** [comment]
@Zomis I did some reading about external file sources, it looks like HTML5 does not support that at all at the current time, so if we plan on using HTML file we need to stick to internal resources. Reference: https://github.com/libgdx/libgdx/wiki/File-handling#file-storage-types

**Comment by Zomis** [comment]
> Would the current JavaScript implementation be able to support this?

What JavaScript implementation? I don't know of any JavaScript implementation ;) (#222 FTW)

This seems to be handled with #369 and the HTML-Client, any reason to keep this issue around?

**Comment by Phrancis** [comment]
No I think we got this covered for now.
