### ISSUE TITLE
Pre-0.6 release clean-up

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#218]
I think there are a few things that ought to be cleaned up so we get a fresh start for 0.7:

- [ ] Organize the JavaScript code files better, e.g., perhaps a `cardshifter-mods` folders in the primary repo directory. And then sub-folders for mod-specific files, e.g., `cyborg-chronicles`.

- [ ] Finish the JS doc and the modding documentation

- [ ] Maybe post JS code for peer review?

- [ ] Update website with new screenshots, game rules and other things specific to 0.6

- [ ] Remove old/unused Game Types from the game (maybe)

Any other ideas are welcome.

**Comment by Phrancis** [comment]
@Zomis I would like to know your opinion on this, mostly on points 1 and 5 as to what we should do.

**Comment by Zomis** [comment]
There is no point 5 :)

1. Organizing JS code files - absolutely. Some of them should really be placed in a specific sub-folder.
4. Removing old/unused game types: Removing them from the game so that they can't be played, sure! Removing them from the code? Not yet. Although I would like to see two different game types in version 0.6 to show the moddability aspect, even if it in this case might just making a little change to the rules and cards (as the clients doesn't yet support much else)

**Comment by Phrancis** [comment]
I meant to reword Point 3, but accidentally deleted instead. So yeah, now there is a point 5 :)

**Comment by Zomis** [comment]
Posting JS code for review: There is a part of that code that I am definitely not proud of, and that I feel contains some code duplication, so possibly yes.

**Comment by Phrancis** [comment]
On 1. Would moving the JS files around require changes to the code much or at all? Is it something I could do fairly easily or would it require your involvement?

On 3. OK, since it's your code I'll let you do that (and get the rep ;)

On 5. I agree, once I finish the documentation and we get files better organized I want to create a mod with different cards and a bit different game style, something a bit more effects-based rather than scrap/upgrade based.

**Comment by Zomis** [comment]
1. as long as you make sure that it works, I don't need to do it. It will probably involve some small changes of the paths [in calls to `load(...)`](https://github.com/Cardshifter/Cardshifter/blob/js-load/extra-resources/JSGame.js#L22)

**Comment by Zomis** [comment]
Maybe change this issue a bit now that we're moving towards Groovy?

**Comment by Phrancis** [comment]
Actually, I think we should probably just start a new one, since the code has changed so much, and it might be a few weeks yet until we're ready for 0.6 using Groovy?

**Comment by Zomis** [comment]
Starting a new one might be a good idea, but there's really only one thing left to add for Groovy to have fully replaced JS, and that's the damage and heal effects. Shouldn't take too long to add.

**Comment by Phrancis** [comment]
Will start a new one soon, don't forget we also need to make Mythos work, which in itself may not be that difficult but will take some time to make the cards and such
