### ISSUE TITLE
JavaFX client performance reported as sub-par

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#219]
[According to @ Mast in chat](http://chat.stackexchange.com/transcript/message/21537539#21537539): 

- "It's seriously lagging my system, which shouldn't happen with a quad i7. My system starts lagging the moment I boot the client"

- "Java is only using 3% or so, but selecting the client from minimization hangs the system for 15sec. 

- "It's still hanging when minimizing and getting back though, that should definitely be fixed"

- "There's nothing visible on my resources monitor during those hangups, so it's not CPU, I/O or memory related"

    Game version: 0.6-SNAPSHOT
    OS: Ubuntu 15.04
    Java version "1.8.0_45" 
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14) 
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by Phrancis** [comment]
Did anyone figure out what the problem was here?

**Comment by Zomis** [comment]
I think the problem was Linux. Could be video drivers or anything. Sounds quite hard to reproduce (although I gotta admit, I have never tried running Cardshifter on Linux)
