### ISSUE TITLE
Groovy-based modding

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#222]
I know that we've recently created the Nashorn-based JS stuff and managed to implement cards quite well there. Some time though, in the future, in a galaxy hopefully not too far away, I'd like to look into using Groovy on the server-side as a way of making mods. I am quite confident that it would be possible, clean, and overall pretty awesome.

**Comment by Phrancis** [comment]
I'm certainly not against looking into it. I'm curious though what we could gain from it specifically?

**Comment by Zomis** [comment]
I think it could potentially improve the moddability significantly.

Groovy can be used to create some really nice DSL's (Domain Specific Languages), for example, it could theoretically be possible to write the following:

    When this creature deals damage to an opponent, you draw a card

And actually have Groovy execute that **as code**

**Comment by Phrancis** [comment]
@Zomis Shall we consider that Groovy has been sufficiently looked into for you to be convinced? ;-)

**Comment by Zomis** [comment]
I will continue to work on making Groovy modding easier, and I think that it will be much cleaner than in JS eventually. So I'm quite convinced, yes. Now the fun part remains of actually implementing it.

**Comment by Zomis** [comment]
It works very well, some features are still missing though, and it will be refactored a bit later on. I really don't think we can do any better than this in terms of moddability.
