### ISSUE TITLE
Cross-mod playing

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#224]
I've been talking to Jay, And there is one thing he really would like to see happen. We both realize it will be **very** difficult to make happen. But the idea is to where I can start a game using Cyborg Chronicles mod, and someone else can start a deck using another mod like Mythos, and *we can play each other*. 

We realize there are all sorts of obstacles for this to happen. Is it realistically even possible?

**Comment by Zomis** [comment]
A friend of mine would actually like to accomplish the same thing, but with Hearthstone and Magic: The Gathering.

Theoretically, it is possible, but there are a bunch of obstacles for it.

Let's take the example of HS & MTG. You play a HS deck, I play a MTG deck.

Here is just some examples of possible obstacles:

- Does this mean that you start with 30 life (HS) and I with 20 (as in MTG) ?
- How should attacking and blocking work? If you are attacking me, do you attack according to the HS system? Can I block according to the MTG system?
- If you play a card, am I allowed to interrupt that with one of my counterspell cards?
- What use will my "Destroy target opponent artifact or enchantment" cards be? You have neither artifacts or enchantments. Or should your Secrets be considered Enchantments and your Mech creatures considered artifacts?

In addition to these obstacles, I suspect that mods will be very unbalanced. Some mods are likely to have some cards that are much more powerful than those found in other mods.

**Comment by Phrancis** [comment]
I figured that would be the case, thanks for looking into it

**Comment by MGS1GreyFox** [comment]
I really am hesitant to even begin to walk down this route. I agree with Simon on his synopsis of this. The potential merging of two separate TCGs, while sound good on paper, just seems like it would be a nightmare. Just the initial hurdle of making the two systems communicate and even attempt to play nice would be huge. On top of that the balancing alone would make the game side with one TCG variant over the other eventually. I think it we even attempted to go down this route, by the time we would get something like a HS V. MTG working it would essentially be a HS clone with MTG cards or vice versa. While it sounds good on paper, I really don't think the final product would be something fun. Just the issue like handling attacks and blocking would make a game feel like one or the other, there is really no way to overcome that without one game taking the features of the other to function properly/ That's just my opinion though.

**Comment by Zomis** [comment]
It is indeed a complex task. I'm leaving it open, but marked with the 'Unclear' milestone, as it's not certain we will ever support this.

**Comment by Phrancis** [comment]
One another hand, I think supporting that and trying to circumvent balance issues would severely impede moddability, as all the games would need to at least use the same core logic, which would be really not good for some of the ideas I have for Mythos. Let's just not go down that road right now.
