### ISSUE TITLE
"onDeath" trigger

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#226]
I was looking at MTG rules and they have a game style called Commander, where a Hero card is chosen as a Commander, and when it is eliminated from play, it returns to a "command zone" where it can be cast again. This would be more or less equivalent to returning to your hand, for all intents and purposes. 

It could probably use a better name, but either way I'd like to be able to do something like this:

            {
                name: "Commander",
                creature: "Bio",
                manaCost: 8,
                health: 6,
                attack: 6,
                onDeath: {
                    summon: {
                        count: 1,
                        card: "Commander",
                        where: "Hand",
                        who: "owner"
                    }
                }
            }

I'm sure there are tons of other creative ways we could use that trigger as well.

**Comment by Zomis** [comment]
Yes, this is especially a common trigger in HS, where it is called "Deathrattle". Definitely something we should support.

**Comment by Zomis** [comment]
Syntax:

    onDeath {
        heal 1 to 'you'
    }

    onDeath {
        summon 3 of 'Cheating shot' to 'owner' zone 'Deck'
    }
