### ISSUE TITLE
'maxInDeck' card property

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#228]
I'd like if we could set an option arbitrary max quantity of any given card, rather than setting that at the mod-level, or more conveniently, overrides the mod's default max quantity. So taking Cyborg Chronicles for example, I can have 3 of any given card in my deck. I might want to make more specialized cards that I only want to allow 1 or 2, or maybe 5.

**Comment by Zomis** [comment]
Shouldn't be too hard to support really. Is partially already supported, just need a good way of applying the value to it.

**Comment by Zomis** [comment]
I plan on supporting this in Groovy.
