### ISSUE TITLE
"probability" card effect argument

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#233]
This is used in many games and we should support this for actions to happen with a certain random probability. Examples (using 0.6 Groovy DSL):

    whilePresent {
        // 25% chance to gain 1 attack
        change ATTACK by 1 probability 25 withPriority 1 onCards {
            card(this)
        }
    }

Or...

    afterPlay {
        // 50% chance to summon Gyrodroid on play
        summon 1 "Gyrodroid" probability 50 ownedBy "you" zone "Battlefield"
    }

**Comment by Zomis** [comment]
I don't think this should be supported for `whilePresent` effects, but can definitely be supported for afterPlay / end of turn and other triggers.

An alternative construct can be:

    afterPlay {
        withProbability(0.5) {
            summon 1 "Gyrodroid" probability 50 ownedBy "you" zone "Battlefield"
        }
    }

**Comment by Phrancis** [comment]
You're right it wouldn't make sense much with `whilePresent`, `onEndOfTurn` is more what I was thinking of. I do like the alternative construct as well.

**Comment by skiwi2** [comment]
Can this not be inherited supported in the "doAction" DSL?

As @Phrancis mentioned it could work as ```summon 1 "Gyrodroid" probability 50 ownedBy "you" zone "Battlefield"```, I'm not seeing objections against it.

**Comment by Zomis** [comment]
It can of course work as 

    summon 1 "Gyrodroid" probability 0.5 ownedBy "you" zone "Battlefield"

I think however that as probabilities is not a common thing to add, that it is better to make it more clear that the probability is present. Just my opinion though, both are very easy to support

**Comment by Phrancis** [comment]
I agree, let's go ahead and use the way you suggested @Zomis

**Comment by Phrancis** [comment]
@Zomis What is the final syntax on this effect? I just realized it has not been documented yet.

**Comment by Zomis** [comment]
Like this:

    withProbability(0.5) {
        summon 1 "Gyrodroid" ownedBy "you" zone "Battlefield"
    }
