### ISSUE TITLE
"pickAtRandom" modifier

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#234]
As discussed [in chat](http://chat.stackexchange.com/transcript/message/21783812#21783812) this would be a modifier to pick a certain effect/attribute at random out of a selection of two or more. Suggested syntax example

    pickAtRandom(
        { summon 1 of "Foo" to 'you' zone 'Battlefield' },
        { summon 1 of "Bar" to 'you' zone 'Battlefield' }
    )

**Comment by Zomis** [comment]
related to #233

**Comment by Zomis** [comment]
Now possible with the following syntax:

        pick 2 atRandom {
            summon 1 of 'Cheating shot' to 'owner' zone 'Hand'
        }, {
            summon 1 of 'Cheating Arms' to 'owner' zone 'Hand'
        }, {
            summon 3 of 'Cheating shot' to 'owner' zone 'Deck'
        }

Note that I made it more flexible by using `pick X`
