### ISSUE TITLE
Target specific card

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#238]
We need to be able to make effects that target one or more specific cards only. For example:

`onCards { card "Foo", "Bar" }`

**Comment by Phrancis** [comment]
Related #237

**Comment by Phrancis** [comment]
Related #235

**Comment by Zomis** [comment]
Also the special: `card(this)`, or as it also can be written: `card this`

**Comment by Zomis** [comment]
Using `cardName 'Foo', 'Bar'` now. I hope that's alright.

To target the card itself, I'm using `thisCard()` for now.
