### ISSUE TITLE
Lethal damage when using a set resource modifier

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#239]
With the implementation of #236 , it is possible to do:

    whilePresent {
        set(HEALTH).to(1).withPriority(2).onCards {
            zone 'Battlefield'
        }
    }

This, however, makes it impossible to kill any cards on the battlefield, because while attacking, cards are first damaged and then it is checked to see if they should be removed or not (based on their health). However, after damaging them, the health is again read as +1, which makes it impossible to kill the cards.

This must be considered a bug, right? Or should it be possible to make cards immortal this way?

**Comment by Phrancis** [comment]
I don't think making cards immortal would be desired, at least not in the foreseeable future, so yes, I think this should be considered a bug. Good thinking, I didn't think about it that way
