### ISSUE TITLE
Effect to all, to X random, etc.

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#246]
Add support for the following:

- [x] All players draw X cards
- [x] *(Do something)* to all entities that match a filter
- [x] *(Do something)* to X random entities that match a filter
- [x] *(Do something)* X times

**Comment by Zomis** [comment]
Example for dealing damage to 2 random:

    onEndOfTurn {
        damage 1 to 2 random {
            creature true
            ownedBy 'you'
            zone 'Battlefield'
        }
    }

**Comment by Zomis** [comment]
Example for `change` and `set`:

    onEndOfTurn {
        change ATTACK by 1 onCards 2 random {
            ownedBy 'you'
            zone 'Battlefield'
        }
        set HEALTH to 1 onCards 2 random {
            ownedBy 'you'
            zone 'Battlefield'
        }
    }

**Comment by Zomis** [comment]
Repeat example:

    onEndOfTurn {
        repeat(3) {
            change ATTACK by 1 onCards 1 random {
                creature true
                ownedBy 'you'
                zone 'Battlefield'
            }
        }
    }

**Comment by Phrancis** [comment]
@Zomis what is the syntax for "all" modifier? Any example?

**Comment by Zomis** [comment]
@Phrancis That's the "default".

For example:

    change ATTACK by 1 onCards {
        ownedBy 'you'
        zone 'Battlefield'
    }

**Comment by Phrancis** [comment]
What about for your initial example "All players draw X cards"?

**Comment by Zomis** [comment]
`drawCard 'all', 4`
`drawCard 'you', 4`
`drawCard 'opponent', 4`
