### ISSUE TITLE
Make systems configuration more fluent

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#247]
Things like this is hard to write and understand:

    useCost(action: PLAY_ACTION, res: MANA, value: MANA_COST, whoPays: "player")

Make the entire `systems` setup easier.

**Comment by Zomis** [comment]
Current line of thought is to refactor the entire `setup` section, rename it to `rules` instead.

Inside the `rules` section:

- use an `init` section for stuff that happens before, or when, game is started. This can be pure code
- `always` section that specifies some systems that are always present, such as `removeDead`, `LimitedHandSize`...
- `turnStart` and `turnEnd` sections that describe what happens when a turn/phase starts or ends.
- `action` sections, one for each action name, that describe those actions. Requirements for being allowed, and what to do when performing the action.

Example `init`:

    init {
        game.players.each {
            it.deck.createFromConfig('Deck')
            it.deck.shuffle()
            it.drawCards(5)
        }
        mulliganIndividual()
    }

Example `turnStart`:

    turnStart {
        apply {
            you.drawCard(1)
            you.mana_max = Math.min(1 + (int) you.mana_max, 10)
            you.mana = you.mana_max
            you.battlefield.forEach {
                it.attack_available = 1
                if (it.sickness > 0) {
                    it.sickness--
                }
            }
        }
    }

Example `turnEnd`:

    turnEnd {
        apply {
            you.battlefield.forEach {
                it.health = it.max_health
            }
        }
    }

Example `action`:

    action('Enchant') {
        allowFor {
            zone 'Hand'
        }
        targets 1 of {
            zone 'Battlefield'
            creatureType 'Bio'
            ownedBy you
        }

        cost SCRAP value card.scrap_cost to card.owner
        cost MANA value card.mana_cost to card.owner
        perform {
            targets.forEach {
                it.attack += card.attack
                it.health += card.health
                it.max_health += card.health
            }
            effectAction()
            destroy()
        }
    }

**Comment by Phrancis** [comment]
I like that a lot, I think going in that direction would make the Game that much easier to mod!

**Comment by Zomis** [comment]
parts of this issue depends on there having been some progress at least to #242
