### ISSUE TITLE
Display effect description and flavor text when card is double-clicked

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#250]
As a consequence of the new Groovy DSL effects, the effect descriptions (and eventually flavor text) bleed out of the cards and mess up the card grid.

A proposed solution was to hide the effect descriptions & flavor text until the user double-clicks the card to display a larger version of it, or the hidden text. Other possible options would be to display the effects & flavor text on mouse hover (similarly to tool tips as we see in many kinds of software).

![bobif](https://cloud.githubusercontent.com/assets/8539648/7884909/ec818b58-05ee-11e5-8c5a-0101235db494.png)

![1okhc](https://cloud.githubusercontent.com/assets/8539648/7885066/e0155ce0-05ef-11e5-847e-815635a1af2e.png)

**Comment by Zomis** [comment]
Tool-tips could definitely work for Desktop platforms, harder to accomplish for mobile ;)

**Comment by Phrancis** [comment]
Is the libGDX version experiencing similar layout issues?

**Comment by Phrancis** [comment]
Guess the more difficult part is how to display the text? I think for now, especially on the JavaFX version, we could probably afford to just open a box where the user double-clicks that displays the text. Especially since eventually we will use libGDX most likely for everything, I don't think we should spend much more time maintaining the JavaFX version

**Comment by Phrancis** [comment]
Old but related - #53

**Comment by Phrancis** [comment]
[This commit](https://github.com/Cardshifter/Cardshifter/commit/cb1631a4c25b239a5512b0efab6e122ed19dd7a3) should help to see where the changes need to be made

**Comment by Phrancis** [comment]
I say we should fix the JavaFX version for 0.6, and work on the libGDX version for 0.7. Anyone opposed?

**Comment by Zomis** [comment]
Fixed for now. Will need a better clean up later on
