### ISSUE TITLE
Separate mana cost and mana upkeep

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#265]
As discussed with Jay, it's not always ideal for cards to have the same mana cost as upkeep cost. Separate these. Possibly with a limit of how big the upkeep cost may be.

**Comment by jacwah** [comment]
Upkeep and cost separated by 210a88b206af1586b413d101db12cce52e963a80 and f0998cd6d7485e4493b0a7733683febffbb357f2. What do you mean by limit?

**Comment by Zomis** [comment]
Good question. Not sure.
