### ISSUE TITLE
Card entity have more than one creature type

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#271]
It should be possible to do something like this:

`card('HeroBot') { creature "Mech"; creature "Hero" }`

Or more elegantly:

`card('HeroBot') { creature "Mech", "Hero" }`

**Comment by Zomis** [comment]
I think that it makes sense to use simple space-separated values here, such as:

    creature "Mech Hero"

Or should `Mech Hero` be treated as one type and `Mech, Hero` treated as two?
