### ISSUE TITLE
"timesPerTurn" modifier

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#276]
Could it be possible to do something like this?

_"Once per turn, do X"_

I think this would be related in part to #270 where you could pick an action.

**Comment by Zomis** [comment]
Elaborate, please. More context!

**Comment by Phrancis** [comment]
@Zomis sorry I was working on submitting another issue, see #277 to give you some context.

**Comment by Phrancis** [comment]
I got clarification on this, this should be part of the `pickAction` issue #270 . I'll comment there
