### ISSUE TITLE
Give a modifier to a card according to some conditions

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#286]
We have a number of [modifiers](https://github.com/Cardshifter/Cardshifter/blob/mods/Documentation/1&#40;%20Card%20Library%20-%20Basics.md#modifiers) and we should allow them to be added upon some conditions being met. Example:

_"If that target unit is a Hero give it Range as well."_

Example pseudo-DSL:

        // If that target unit is a Hero give it Range as well.
        ifTarget (creatureType: "Greek Hero") {
            set ranged() toCards { target() }
        }

**Comment by Phrancis** [comment]
@Zomis would it be very difficult to implement a sort of if/else logic for card effects? I'm thinking since that logic is already native to Groovy might not be too complicated to come up with something useable?

**Comment by Zomis** [comment]
I think we should be able to come up with something, but I feel that the whole if/else thingy has been mentioned elsewhere, for example #261

**Comment by Phrancis** [comment]
Good point. Let's generalize #261 a bit more and see what we come up with for this kind of logic.
