### ISSUE TITLE
"change" & "set" on spells

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#291]
At the current time, it is not possible AFAIK to use `change` or  `set` as part of a spell. The problem appears to be related to `targets`. I tried both of the following syntaxes, both are throwing a server-side error of this type:

    groovy.lang.MissingMethodException: No signature of method: mythos.common.afterPlay() is applicable for argument types: (mythos.common$_run_closure12$_closure25) values: [mythos.common$_run_closure12$_closure25@d9e9663]

Syntaxes tried:

    spell {
        targets 1 {
            creature true
            ownedBy "opponent"
            zone "Battlefield"
        }
    }
    afterPlay {
        set HEALTH to 0 to { targets() }
    }

Or:

    spell {
        targets 1 {
            creature true
            ownedBy "opponent"
            zone "Battlefield"
        }
    }
    afterPlay {
        set HEALTH to 0 to targets
    }

**Comment by Zomis** [comment]
This seems to me like a bug, AFAIK this should be working.

**Comment by Zomis** [comment]
This should work:

    spell {
        targets 1 {
            creature true
            ownedBy "opponent"
            zone "Battlefield"
        }
    }
    afterPlay {
        set HEALTH to 0 to targets
    }

Please provide additional details why it doesn't.

**Comment by Zomis** [comment]
This works for me:

    card('Test') {
        manaCost 1
        spell {
            targets 1 cards {
                creature true
                ownedBy "opponent"
                zone "Battlefield"
            }
        }
        afterPlay {
            set HEALTH to 0 on targets
        }
    }

The problem seems to have been that `targets 1 {` should be `targets 1 cards {`
