### ISSUE TITLE
Effect "target" one or more specific cards

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#295]
We've been talking [in chat](http://chat.stackexchange.com/transcript/message/22098048#22098048) about ways to target one or more cards with an action (other than Attack/Scrap) or an effect (like changing a resource, similar mechanics to Enchantment cards; perhaps we can re-use some of the same code?)

**Comment by Lokkij** [comment]
I'd like to propose the following syntax:
```
// Generic syntax:
effect to n targets { 
    filters
}

// Example usage:
damage 4 to 2 targets {
    creature true
    zone "Battlefield"
}
```

We could then replace `effect onCards { filters }` with `effect on all targets { filters }` for consistency.

**Comment by Phrancis** [comment]
Another possible syntax, if implementing that is easier, would be to include targets inside the filter, either way would be fine though really.

Example:

`onCards { targets 1; creature true; zone "Battlefield" }`

**Comment by Zomis** [comment]
Sorry @Phrancis, I don't think putting `targets x` inside the same 'closure' as the filter is a good idea. I like Lokkij's suggestion better.

**Comment by Phrancis** [comment]
@Zomis no worries, let's do it his way then :)

**Comment by Phrancis** [comment]
I think this is somewhat similar/related to #287

**Comment by Zomis** [comment]
@Phrancis Now that I think of it, how is this issue different from the way spells are defined as it is today?

For example, this is a valid card:

    card('E.M.P.') {
     "Electromagnetic pulse that damages electronic circuitry."
     manaCost 8
     // damage 2 to up to 10 Mechs on the Battlefield
     spell {
      targets 1 to 10 cards {
       creatureType "Mech"
       zone "Battlefield"
      }
     }
     afterPlay {
      damage 2 on targets
     }
    }

**Comment by Phrancis** [comment]
Yup, I think you're right!
