### ISSUE TITLE
Including the right file

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#297]
If there's one `spells.groovy` in the mod directory and one in the general `mods` directory, the wrong one can be included. This has caused a headache for poor @Phrancis already.

Note that files are included both on `include 'xyz'` and on `cardset 'xyz'`. Perhaps use different file extensions to solve this confusion.

**Comment by jacwah** [comment]
In line with what is written above, how about making `cardset 'spells'` search for `spells.cardset`? In other words, keep `include` as it is and force `cardset` to look for files with the `.cardset` extension.

An alternative solution could be to separate the file searching logic for the two keywords and have `cardset` look in the local mod directory (e.g. `mods/mythos/`) and `include` in the parent directory (`mods/`).

    new File(modDirectory, fileName),
    new File(modDirectory.getParentFile(), fileName),
    new File('mods/' + fileName),
    new File(fileName),

These are the directories being searched right now, see [GroovyMod:47](https://github.com/Cardshifter/Cardshifter/blob/groovy/cardshifter-core/src/main/java/com/cardshifter/core/groovy/GroovyMod.groovy#L47).

I think the file extension solution will be easier to implement and understand.

**Comment by jacwah** [comment]
We came to the conclusion to use `.cardset` for cardsets and keep everthing else `.groovy` in chat. The conversation starts [here](http://chat.stackexchange.com/transcript/message/23686915#23686915).

- [ ] Change file extension of all cardset files in `extra-resources`
- [ ] Change implementation of `cardset` to look for `.cardset` files
- [ ] Add info to the documentation

**Comment by jacwah** [comment]
Doesn't look like there's any documentation to change :+1:
