### ISSUE TITLE
Client crashes when starting local game without selected opponent

### ISSUE THREAD

**Issue by Lokkij** [Cardshifter/Cardshifter#299]
The client throws a `NullPointerException` when attempting to start a local game without a selected AI opponent.

**Comment by Phrancis** [comment]
Related: Improve game UX  #181

**Comment by Phrancis** [comment]
I didn't think not choosing an opponent or game type made the client crash, at least it didn't in the past, if just posted a message to the chat there to advise to choose an opponent/game type. It did raise an NPE but it didn't crash, and worked fine after making a selection. Can you please clarify?
