### ISSUE TITLE
HTML5 version - Should we support it?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#301]
It appears there have been several features which would be beneficial, but are not supported by libGDX's HTML5 versioning. Among those are:

- External sources for card images (see issue #217)
- Support for Groovy [(more info)](http://www.badlogicgames.com/wordpress/?p=3336)

This brings up a question I think we need to address: What do we gain by offering support for HTML5, where we would not otherwise be better off _not_ offering support for HTML5, but having access to better tools and features to benefit potentially every other version?

**Comment by Zomis** [comment]
HTML5 is very easily accessable, it is easy to just start using without the need to download or install anything. This is the main reason for supporting it IMO.

An alternative might be to have LibGDX only focus on the other platforms, and then implement some other client for HTML5, that would however mean yet another client that needs support.

**Comment by Phrancis** [comment]
@bazola What are your thoughts on this one?

**Comment by Phrancis** [comment]
In light of recent discussion in chat about making a HTML/CSS/JS browser-based client from scratch, rather than using libGDX, what should we do with this? 

Perhaps if we can use libGDX for what it's really good at, and roll our own HTML client; best of both worlds?

**Comment by Phrancis** [comment]
I think with the development of the [HTML-Client](https://github.com/Cardshifter/HTML-Client) we no longer need to concern ourselves about supporting GWT at all now. libGDX I think should be focused on non-browser version.
