### ISSUE TITLE
No Game Types (mods) showing in lobby

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#308]
As of snapshot from 2015-06-20, no game types are available to select from. 

![screen shot 2015-06-20 at 8 24 02 pm](https://cloud.githubusercontent.com/assets/8539648/8269841/30dddd58-178b-11e5-96fe-0637943931c2.png)

**Comment by Phrancis** [comment]
Here is a full server log: http://pastebin.com/2eqdMR5Q

**Comment by Zomis** [comment]
According to the server log, it seems like the mods are identified and loaded, so this might be a client-side problem:

    [2015-06-20 20:23:40,331]  INFO Log4jAdapter [    Conn-0] (     Log4jAdapter.java: 16) - Send to Phrancis: AvailableModsMessage [mods=[Mythos, Cyborg-Chronicles]]
