### ISSUE TITLE
Document how to get the project building and running

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#309]
It's not intuitive for a new developer/modder to get the program imported, building and running. We need documentation.

**Comment by Zomis** [comment]
I think the first screenshot at https://github.com/Cardshifter/Cardshifter/wiki/2--Running-the-application is showing the wrong working directory, I believe it should be in `extra-resources`

**Comment by Phrancis** [comment]
You're right, I'll fix that tonight. Should be `.../Cardshifter/extra-resources` right?

**Comment by Phrancis** [comment]
This has been documented pretty well:

[1- Getting started with development](https://github.com/Cardshifter/Cardshifter/wiki/1--Getting-started-with-development)

[2- Running the application](https://github.com/Cardshifter/Cardshifter/wiki/2-%20Running-the-application)

**Comment by Phrancis** [comment]
Documentation about branches has been added in wiki: [Branches (Git)](https://github.com/Cardshifter/Cardshifter/wiki/Branches-%28Git%29)
