### ISSUE TITLE
Some card attributes not loading on my machine (release 0.6)

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#310]
When I run 0.6 official (as of 2015-06-21) a number of attributes are errorring, including creature, flavor text, mana cost, scrap cost. It seems to raise an error like:

    Missing method: creature on Entity #3 with args [Common]

As of the time of this writing, it only happens on my machine. The error doesn't happen if I run it from IDE, only from the packaged zip file(s).

**Comment by Zomis** [comment]
My current possible suspicions: Line endings, Locale, case-sensetive filenames.

This needs to be tested on more platforms to determine what might be, and what might not be, the cause.

I am on Windows, @Phrancis is using Mac OS. We need more Mac + Linux people to test the latest release.

**Comment by Phrancis** [comment]
To clarify, I was able to run directly from IDEA, and to run with my own Gradle generated JARs, but not with @Zomis JARs.

**Comment by Zomis** [comment]
It works for Lokkij (Windows) and for bazola (Mac OS). Still no one that has experienced the same problem as you.

**Comment by Phrancis** [comment]
Is there a way to `java -jar` with a stack trace or debug information?
