### ISSUE TITLE
Test fails on "spell { targets n {} }"

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#324]
A card like this one in Mythos/common.groovy

    card('Spring of Rejuvenation') {
        manaCost 5
        // Target unit gains +3 health
        spell {
            targets 1 {
                creature true
                ownedBy 'you'
                zone 'Battlefield'
            }
        }
        afterPlay {
            heal 3 on targets
        }
    }

Generates an inspection warning like such in IDEA:

![screen shot 2015-07-11 at 3 38 37 pm](https://cloud.githubusercontent.com/assets/8539648/8635109/f7ae1c6a-27e2-11e5-933c-124161b89130.png)

When `./gradlew clean build -debug` generates the following test failure:

    15:37:53.488 [DEBUG] [TestEventLogger] com.cardshifter.core.GroovyTest > com.cardshifter.core.TestUtils$5.multithreaded test FAILED
    15:37:53.489 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: common.spell() is applicable for argument types: (common$_run_closure18$_closure49) values: [common$_run_closure18$_closure49@1ab7bcae]
    15:37:53.490 [DEBUG] [TestEventLogger]     Possible solutions: sleep(long), split(groovy.lang.Closure), grep(), every(), inspect(), grep(java.lang.Object)
    15:37:53.490 [DEBUG] [TestEventLogger]         at com.cardshifter.core.modloader.GroovyMod.declareConfiguration(GroovyMod.java:52)
    15:37:53.490 [DEBUG] [TestEventLogger]         at com.cardshifter.core.TestUtils$3.run(TestUtils.java:111)
    15:37:53.490 [DEBUG] [TestEventLogger]         at com.cardshifter.core.TestUtils$5.runTest(TestUtils.java:176)
    ...

This is the test that fails:

![screen shot 2015-07-11 at 3 43 38 pm](https://cloud.githubusercontent.com/assets/8539648/8635125/aa09528a-27e3-11e5-86a4-1893e5801489.png)

**Comment by Zomis** [comment]
It seems like the correct syntax might be:

        targets 1 cards {
            creature true
            ownedBy 'you'
            zone 'Battlefield'
        }

**Comment by Zomis** [comment]
This seems to work for me:

    card('Test') {
        manaCost 1
        spell {
            targets 1 cards {
                creature true
                ownedBy "opponent"
                zone "Battlefield"
            }
        }
        afterPlay {
            set HEALTH to 0 on targets
        }
    }
