### ISSUE TITLE
Enchantment cards require scrap related resources to function

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#325]
I found the problem trying to add enchantment cards for Mythos. I added `include 'enchantments'` and  `ENCHANT_ACTION = "Enchant";` to Game.groovy but kept getting failed tests. I had to `include 'scrap'` and `SCRAP = createResource("SCRAP")`, `SCRAP_COST = createResource("SCRAP_COST")` for it to build successfully.

I think this should be fixed so that modders who have no use for the scrap-related resources aren't required to include it, or otherwise, if preferable, include scrap resources in all mods for compatibility... Thoughts?

**Comment by Zomis** [comment]
The enchantment approach will be re-designed a bit, this should be incorporated then as well. Issues related to that are #287 and #247.
