### ISSUE TITLE
"change" and "set" inside "pick n atRandom"

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#326]
The following effect causes failures in `com.cardshifter.core.GroovyTest` :

    onEndOfTurn {
        pick 1 atRandom (
                { change HEALTH by 1  on { thisCard() } },
                { change ATTACK by 1  on { thisCard() } },
                { change HEALTH by -1 on { thisCard() } },
                { change ATTACK by 2  on { thisCard() } },
                { set SICKNESS to 2   on { thisCard() } }
        )
    }

Failure header below, and here is [full stack trace](http://pastebin.com/Fx9K8LUz).

    13:20:59.672 [DEBUG] [TestEventLogger] com.cardshifter.core.GroovyTest > com.cardshifter.core.TestUtils$5.summon on battlefield FAILED
    13:20:59.675 [DEBUG] [TestEventLogger]     groovy.lang.MissingPropertyException: No such property: HEALTH for class: EffectDelegate
    13:20:59.675 [DEBUG] [TestEventLogger]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
    13:20:59.675 [DEBUG] [TestEventLogger]         at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
    13:20:59.675 [DEBUG] [TestEventLogger]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:304)
    13:20:59.675 [DEBUG] [TestEventLogger]         at mythos.hindu$_run_closure5$_closure16$_closure17.doCall(hindu.groovy:106)
    13:20:59.675 [DEBUG] [TestEventLogger]         at mythos.hindu$_run_closure5$_closure16$_closure17.doCall(hindu.groovy)
    13:20:59.676 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

This analogous, but not quite the same, as this effect, which does work fine:

    onEndOfTurn {
        pick 1 atRandom (
            { heal 2 on 'you' },
            { heal 1 on 'opponent' },
            { damage 1 on 'you' },
            { damage 2 on 'opponent' }
        )
    }

**Comment by Zomis** [comment]
The problem is caused by `HEALTH` being referred inside a `change XXX by` inside a `pick atRandom`. This is probably related to the delegation strategies in Groovy. I hope they can be changed without breaking anything, otherwise we should implement a `missingProperty` method in the `EffectDelegate` class.
