### ISSUE TITLE
Player has a negative scrap

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/Cardshifter#328]
![negative thing](https://cloud.githubusercontent.com/assets/8549957/8856855/6d86a6f8-313b-11e5-80d4-b43bb5a08c8c.png)

*Note: It was originally -5 but I discarded a card.*

Here is the server log (Note that it may contain excess information):

http://pastebin.com/t4R1wBDu

**Comment by Phrancis** [comment]
@SirPython Do you recall if the game let you cast an enchantment card (any card with a Scrap Cost > 0) which exceeded the SCRAP you had available at the time?

**Comment by Zomis** [comment]
Unfortunately, that log is only from the client and not from the server, and does not mention any `SCRAP` values, so that doesn't help.

**Comment by SirPython** [comment]
@Phrancis No, I do not think it did. Here is what I remember:

1. I notice the -5 scrap
2. I scrap a card with a +3
3. Screenshot

There might have been other things before/after/between those steps.

**Comment by SirPython** [comment]
@Zomis I apologize. At first, I was trying to copy something from the console. Then, to copy I hit CRTL-C which shut down the game. I figured that the client log would also be helpful, because it included what information was send and what information it recieved.

**Comment by Zomis** [comment]
Those series of actions make sense, I'm mostly wondering what happened *before* there was the -5 scrap.

**Comment by SirPython** [comment]
@Zomis This may be completely biased, but I think it was either:

- I was attacked by an enemy card.
- I played a card that required scrap points.

I am leaning towards the first one a little.

**Comment by Zomis** [comment]
I managed to reproduce the bug by playing a card that required scrap. Somehow it seems that you're allowed to that despite not having the scrap available.
