### ISSUE TITLE
Tried to use "Deck Builder" and got NullPointerException

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/Cardshifter#329]
Here is what happened:

1. I opened up Cardshifter.
2. I logged in to the `dwarftowers.com` server.
3. I clicked "Deck Builder" at the top.
4. To the chat feed, this was logged:

<br>

    [time] SERVER ERROR: java.lang.NullPointerException

**Comment by Zomis** [comment]
This probably happens because you haven't selected a mod to play yet (different mods have different possible usable cards). I thought there already was an issue for this, but there doesn't seem to be.

**Comment by SirPython** [comment]
@Zomis That could be the issue. Afterwards, I tried to start the game and was given the error message that I still needed to select a mod.
