### ISSUE TITLE
Add @example JavaDoc tag

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#332]
I will be using an `@example` keyword throughout API and perhaps other documentation. If possible please have it added to the pom or Gradle so that it is recognized as a valid JavaDoc tag.

Example usage: 

	/** 
	 * Constructor.
	 * @param   username  the incoming user name passed from client to server, not null
	 * @example Message:  <code>{ "command":"login","username":"JohnDoe" }</code>
	 * @example Response: <code>{"command":"loginresponse","status":200,"userId":6,"message":"OK"}</code>
	 */
	public LoginMessage(String username) {
		super("login");
		this.username = username;
	}

**Comment by Zomis** [comment]
I don't think it's worth the time to fix this. At the moment, I don't think it is a problem to do it like this, if it would ever be a problem, then change the documentation style.
