### ISSUE TITLE
Triggered action for a card to eliminate itself / perish

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#344]
An effect to make a card be removed from the Battlefield is desirable for certain kinds of effects. In particular, I ran into this issue with [Self-upgrading cards](https://github.com/Cardshifter/Cardshifter/blob/mods/extra-resources/mods/Cyborg-Chronicles/mechs.groovy#L167) where the only possible workaround to make the initial card be removed was to `onStartOfTurn { set HEALTH to 0 on { thisCard() } }` which in itself _can_ work, but not predictably. 

For instance, if another card has a fairly common effect like `whilePresent { change HEALTH by 1 withPriority 1 on { ... }` which affects the card trying to set its own health to 0, either the card will remain in play, or the server will outright lock-up because it can't perform that action. (it's not been very reliable as to which happens when, but that is an issue for another day perhaps).

In any event, I suggest an action function like `perish()` which would override any card health values and simply remove the card into the graveyard, regardless of its health or whatever effects are present that may affect its health. 

This would also be an interesting action to have available inside `pick n atRandom {...}` blocks along with the more standard triggers.

**Comment by Zomis** [comment]
I thought there was a `destroy()` effect already... if not, that should be added.

**Comment by Phrancis** [comment]
I [searched the repository](https://github.com/Cardshifter/Cardshifter/search?utf8=%E2%9C%93&q=destroy) but didn't seem to appear there was such an action, although `destroy()` is used in other places. Do you think it would work as part of the DSL as well? What would the syntax be? Here is a card that would use that, for instance:

```groovy
card("Upgrado Mk I") {
    creature "Mech"
    flavor "Upgrades itself on each new turn up to Mk V."
    attack 1
    health 3
    sickness 0
    manaCost 3
    scrap 1
    onStartOfTurn { summon 1 of "Upgrado Mk II" to "you" zone "Battlefield" }
    onStartOfTurn { set HEALTH to 0 on { thisCard() } }
}
```

**Comment by jacwah** [comment]
Do you prefer `perish()` or `destroy()`?

**Comment by Phrancis** [comment]
I think `perish()` conveys the message better that it destroys itself (as in, it's not suggesting it should expect a target)
