### ISSUE TITLE
Pass card image paths from server to client

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#346]
I've been trying to think for a while what would be a good moddable way to include card images, and this idea came to mind. Right now when a server starts a game it passes JSON card data extracted from the Groovy cardsets that looks like this for each card:

    {
      "MAX_HEALTH" : 10,
      "SICKNESS" : 1,
      "MANA_COST" : 30,
      "ATTACK" : 3,
      "HEALTH" : 10,
      "ATTACK_AVAILABLE" : 1,
      "flavor" : "The Great Grandfather, Emperor of all Deities, Vanquisher of Evil.",
      "name" : "JADE EMPEROR",
      "description" : "Give creatures of type Chinese owned by you on Battlefield 3 HEALTH\nGive creatures on Battlefield -1 ATTACK\n",
      "type" : "Chinese God"
    }

My idea would be to add an extra string field in Groovy like `imagePath` that would pass along the path to the image for that card (or a default image path is such data is absent). I think this might be possible to use for both the HTML client and libGDX clients, assuming the images themselves are included as part of each project. 

Something like this in Groovy, which would pass the full path string to the client to retrieve the actual images:

    card('JADE EMPEROR') {
        creature 'Chinese God'
        flavor 'The Great Grandfather, Emperor of all Deities, Vanquisher of Evil.'
        imagePath 'images/mods/mythos/chinese/jade-emperor.jpg'
        maxInDeck 1
        health 10
        sickness 1
        manaCost 30
        attack 3
        whilePresent {
            change HEALTH by 3 withPriority 1 on {
                creatureType 'Chinese'
                ownedBy 'you'
                zone 'Battlefield'
            }
            change ATTACK by -1 withPriority 2 on {
                creature true
                zone 'Battlefield'
            }
        }
    }

Can this be done? Would this be practical?

**Comment by danpantry** [comment]
Could we have a consistent JSON style? The standard is `foo_bar_baz` as opposed to `FOO_BAR_BAZ`. This would make things easier to reason about when consuming the API.

**Comment by jacwah** [comment]
@danpantry The upper case attributes are resources. They must all have have upper case names for some reason. Quoting [the DSL docs](https://github.com/Cardshifter/Cardshifter/blob/mods/Documentation/2-%20Card%20Library%20-%20Effects.md#resources):

>The name of the resource must always be ALL_CAPS_WITH_UNDERSCORES.

I guess this convention makes it easier to distinguish them from other things in JSON as well.

**Comment by Phrancis** [comment]
@jacwah @danpantry :

The resources in SHOUT_CASE are those passed from the universal ECS resource map in core, as opposed to the lower case values which are from the mod intended either as functional identifiers (i.e., `name`, `type`) or just text to display to the user (i.e., `flavor`, `description`). 

Hope this helps.

**Comment by Zomis** [comment]
Technically, the resources don't need to be with ALL_CAPS, that's just what I used originally (they used to be Java enum values once upon a time, where the naming convention says to do it like that). They can absolutely be shown lowercase. But all this is irrelevant to the actual issue here.

Specifying the full mod-dir every time might be a bit excessive, `imagePath 'chinese/jade-emperor.jpg'` perhaps?

**Comment by Phrancis** [comment]
@Zomis Yeah we can specify the full path client-side, actually, that will be more flexible. I think `modname/cardset/image.jpg` would probably work best, IMO.

As far as implementation, I'd like to perhaps just recycle the same code we use for `flavor` any objection?

**Comment by danpantry** [comment]
Start the image path with `/`. That way you can easily append it to a chosen base path or omit the base url and call the current HTTP host (if you're in a browser).

**Comment by Phrancis** [comment]
This is implemented. Recommended usage is:

    card('Zeus') { imagePath 'mods/mythos/zeus.jpg '}

**Comment by Phrancis** [comment]
I'm starting to test this out. I will add instructions for this to the modding documentation after I get the hang of it.
