### ISSUE TITLE
Clean up Waffle.io board

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#351]
I recently looked through this repo's [Waffle.io page](https://waffle.io/Cardshifter/Cardshifter). I thinks it's a bit unclear what the different categories mean. "Ready" only has 9 very old issues, it looks like it isn't used anymore.

I think all the categories should have a short description of what they are for and how to use them. If Ready is indeed not used anymore I think it should be removed.

[Waffle Workflow](https://github.com/waffleio/waffle.io/wiki/FAQs#waffle-workflow) from their FAQ might be of interest. In their example [here](https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking) they have a category "Needs review" - this is maybe useful for Cardshifter too.

**Comment by Zomis** [comment]
I think another question is whether or not we should continue using Waffle at all. There's quite many issues open so that it is hard to get an overview of them there. I tend to use Github these days for issue overview.

**Comment by jacwah** [comment]
I wasn't a part of this project when the Waffle board was introduced, but I haven't really felt any need for it. I think milestones and labels on Github are a good way to get an overview of issues. As far as I understand, Waffle is intended for repositories with a more strict workflow than ours. I can see it being useful for tracking features through different stages (dev, review, QA, etc) though.

If there's anyone actively using Waffle I think it's worth keeping, but otherwise we could just as well get rid of it as @Zomis brought up.

**Comment by Zomis** [comment]
Waffle board no longer used. Waffle-related tags has been cleared.
