### ISSUE TITLE
Receiving two of the exact same message.

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/Cardshifter#355]
I was doing a little experimenting with the server and what messages it sends as soon as a game starts for Mythos. These are the messages that were received from the server:

    controller.js:31 1. zoneChange
    controller.js:31 2. card
    controller.js:31 3. zoneChange
    controller.js:31 4. card
    controller.js:31 5. zoneChange
    controller.js:31 6. card
    controller.js:31 7. zoneChange
    controller.js:31 8. card
    controller.js:31 9. zoneChange
    controller.js:31 10. card
    controller.js:31 11. zoneChange
    controller.js:31 12. zoneChange
    controller.js:31 13. zoneChange
    controller.js:31 14. zoneChange
    controller.js:31 15. zoneChange
    controller.js:31 16. player
    controller.js:31 17. player
    controller.js:31 18. zone
    controller.js:31 19. zone
    controller.js:31 20. zone
    controller.js:31 21. card
    controller.js:31 22. card
    controller.js:31 23. card
    controller.js:31 24. card
    controller.js:31 25. card
    controller.js:31 26. zone
    controller.js:31 27. zone
    controller.js:31 28. zone
    controller.js:31 29. zone
    controller.js:31 30. resetActions
    controller.js:31 31. useable
    controller.js:31 32. resetActions
    controller.js:31 33. useable

There is one problem: 19 and 26 are identical messages. They both look like this:

    command: "zone"
    entities: Array[25]
    id: 112
    known: false
    name: "Deck"
    owner: 111
    size: 25

<hr>

Extra information: I got this message list three separate times. On the second time, one of the `zone`s group of messages (26-29) was missing. Perhaps this was 26.

There must be something wrong in the server that is causing the server to occasionally send a repeat message.

**Comment by Zomis** [comment]
Today I discovered that I was sent duplicate `UpdateMessage`s. Not sure if it is related or not.

**Comment by Zomis** [comment]
I believe this has been resolved now.
