### ISSUE TITLE
Include commit hash in snapshots

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#361]
It's always possible to know the exact code a release was built from because of tags, but the only identification of a snapshot is the version number preceding it and the date it was built. This is not enough, as shown by the recent confusion in #353.

I think the easiest solution would be to create a text file in the root of the package archive containing the commit hash and optionally the branch name. It could be called `version` or similar. An easy was to get this information is parsing the first line of `git log` and the asterisk line of `git branch`.

    # Unix shell example
    $ git log | head -n 1
    commit ed3a80ba54cf99fbf4a3fc05eb6ebca853f1684b
    $ git branch | grep '*'
    * develop

**Comment by Zomis** [comment]
There are gradle plugins that can be used to interact with git. Should be possible to use that to find out what the current branch and commit SHA is.
