### ISSUE TITLE
Add imagePath attribute to cards in mods

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#369]
I talked to @jay1148 and he will provide us generic logos for Cardshifter, Cyborg Chronicles and Mythos that can be used as placeholders until a card has an image of its own. Eventually, most if not all cards will have an image of their own. This will not require any coding, just adding this attribute to each card.

**Comment by Zomis** [comment]
see https://github.com/Cardshifter/Cardshifter/commit/acb3b4482ba1f47ca657c826d0c2ac4cd9947772

**Comment by Zomis** [comment]
All that's missing is the actual images

**Comment by Phrancis** [comment]
I'm making reasonable progress on card images and should be done within a day or two for everything that will go under the web client.

**Comment by Phrancis** [comment]
This is done as of today
