### ISSUE TITLE
ResourceRetriever: has doesn't behave the same way as getOrDefault

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#372]
I ran into this issue when writing f0998cd6d7485e4493b0a7733683febffbb357f2. `MANA_UPKEEP.retriever().has(entity)` returned true even though `manaUpkeep` was never set for that card. The workaround I made is copy pasta from `ResourceRetriever.getOrDefault` which works properly.

Make `has` use the same logic as `getOrDefault` when figuring out if a resource is set.

**Comment by Zomis** [comment]
I don't think `has` *should* function exactly the same. The reason why I suggested to use `has` was that I would have expected `has` to return false if no value was set, but true if `manaUpkeep` had been *explicitly* set to zero. (or perhaps that should be another method, `isSet`?)

Thanks for reporting it.

**Comment by jacwah** [comment]
OK, so this is not what `has` is for?

In that case I suggest we add an `isSetFor(Entity)` method to `ResourceRetriever` that behaves like `getOrDefault`.

**Comment by Zomis** [comment]
When you say 'behaves like `getOrDefault`', how exactly do you mean? How would you turn that into a boolean?

**Comment by jacwah** [comment]
> the same logic as getOrDefault when figuring out if a resource is set.

This is what I mean. `get` -> `true`, `Default` -> `false`.

If an entity has a resource set explicitly it should return true for that resource and entity.

    card() {
        resource 0
    }

`RESOURCE.retriever().isSetFor(card) -> true`
`ANOTHER_RESOURCE.retriever().isSetFor(card) -> false`

**Comment by Zomis** [comment]
Right, then we mean the same thing.
