### ISSUE TITLE
What should we do with JavaFX and libGDX issues?

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#375]
This question was raised by @Zomis [in chat](http://chat.stackexchange.com/transcript/16134?m=23696584#23696584). I think it's worth to collect our thoughts in one place.

![Chat screenshot](https://cloud.githubusercontent.com/assets/3816754/9529609/8d771a5c-4cfb-11e5-89c4-0c56014bd477.png)

I think at least some Java FX issues can be closed as **wontfix**. Examples below:
- #57 Refactor Cardshifter-FX
- #220 Winning screen
-  #146 Mulligan should automatically activate

These are issues that add features or want to make big changes to the client. I don't think time should be spent on that as the Java FX client is more or less abandoned.

Some issues apply to all clients and could maybe have a **client** label instead of **javafx libgdx**.
-  #212 Implement "discard pile" concept
-  #175 Player Factions/Classes/etc.
-  #110 Observe other games

---

As others have already mentioned: I think the libGDX client can be useful for mobile support as webapps usually don't work as well on there. Maybe the development with libGDX should focus more on that instead of being a jack of all trades.

**Comment by Zomis** [comment]
The problem with the LibGDX client is that it would require **a lot** of work to get it to the state the HTML Client is at today. I think we should put that client on the shelf for now and maybe look back at it at a later time. The development of it hasn't really come very far. I feel that the HTML-Client has much more potential than the LibGDX client.

I'd prefer to push back the milestones for both the LibGDX and JavaFX clients waaaay back (post 1.0), and at the same time close some of them as 'wontfix', and also copying some of the issues into the [Cardshifter/HTML-Client repository](http://github.com/Cardshifter/HTML-Client).

**Comment by Zomis** [comment]
Created a new [postponed milestone](https://github.com/Cardshifter/Cardshifter/milestones/Postponed) where lots of these issues has been added.

**Comment by jacwah** [comment]
Should #102 still be on the 0.6.2 milestone?

**Comment by marcandregirard** [comment]
Since I've worked on #437  and #436, some issue will need more than being in the postpone milestone. The GDX client specific issue will have to be moved. For the Java-FX one, since I did not create a new repo for the client, we could just delete the issues. 

Anyway, there is clearly a need to re-organize the issue.
