### ISSUE TITLE
Change 'ok' to 'success' in Groovy testing DSL

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#377]
[Pointed out by @Phrancis:](http://chat.stackexchange.com/transcript/message/23718849#23718849)
>I prefer more descriptive words than ok, e.g., success vs. failure, or allow vs. deny

As the opposite is 'failure', I think 'success' makes much more sense than 'ok'.

    uses 'Use' on spell withTarget targetCreature ok

Should become

    uses 'Use' on spell withTarget targetCreature success

**Comment by jacwah** [comment]
I think I was a bit confused about what `ok` does when I opened this issue. What I really wanted to change was the syntax of `expect`.

    expect ok when uses 'Use' on spell withTarget targetCreature success

I don't think there's any point in writing this though, as it would have the same effect as skipping the `expect`.

**Comment by Zomis** [comment]
[Quoting jacwah:](http://chat.stackexchange.com/transcript/message/23806247#23806247)

> documenting it (#371) is way more important and will clear some things up. Not sure whether it will need changing or not, but I think that question will become clearer when the DSL is documented.
