### ISSUE TITLE
Generic ErrorMessage

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#379]
*[Original chat discussion](http://chat.stackexchange.com/rooms/16134/conversation/errormessage-discussion) between me and @Zomis.*

There are lots of reasons why a request from a client may fail. Currently errors are communicated in a range of different ways:

- `ChatMessage`: "You cannot invite yourself."
- `ServerErrorMessage`: "Invalid gameType specified."
- `WelcomeMessage`: "User name invalid"

Generally, a client will want to handle all errors in a similar way. The server should not enforce a particular one (with `ChatMessage`).

Create a generic outgoing `ErrorMessage` and use it instead of other constructs currently used. It should include some indication whether it was caused by the client or the server.

    # Possible implementation
    {
        "command": "error",
        "message": "You cannot invite yourself.",
        "cause": "client"
    }

**Comment by Zomis** [comment]
Just to be clear: The existing `ServerErrorMessage` can be changed to this.

**Comment by Zomis** [comment]
What is the progress on this one, I think the `WelcomeMessage` was removed at least, right?

**Comment by jacwah** [comment]
Nothing has been changed AFAIK. `WelcomeMessage` exists on `develop`.
