### ISSUE TITLE
Enchanting health only lasts until end of turn

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#384]
Ever since we changed #287, enchantments in Cyborg-Chronicles only lasts until end of turn.

**Comment by Zomis** [comment]
The reason for this is that before https://github.com/Cardshifter/Cardshifter/commit/f756745af2ecac703915111cb87dbe660392d866, it was `it.health += card.health` and `it.max_health += card.health`, but now only `health` is enchanted, not `max_health`.

**Comment by Zomis** [comment]
even more precise commit: https://github.com/Cardshifter/Cardshifter/commit/9b5deb04db8da63442102fed905c3c99e3cfa968

**Comment by jacwah** [comment]
I see two possible approaches here:

1) Edit the affected enchantments:
```Groovy
card('Body Armor') {
    flavor "Steel-reinforced armor to absord damage from blows and shots."
    enchantment()
    afterPlay {
        change HEALTH by 2 on targets
        change HEALTH_MAX by 2 on targets // Add this line
    }
    scrapCost 1
}
```
2) Add some way in the syntax to change both values at once. The most obvious way would be `change HEALTH, HEALTH_MAX by 2 on targets`. Could also have a "virtual resource" like `HEALTH_ALL` that modifies both resources behind the scenes.

I think we should fix this bug by doing 1) and then possibly think more about 2) for the future.

**Comment by Zomis** [comment]
Funny, I was thinking that 2) would be the preferred way of fixing this :)

I totally agree about your two possible approaches though, just one thing to add: `HEALTH_ALL` could be implemented as an *array* of `HEALTH` and `HEALTH_MAX`.

**Comment by jacwah** [comment]
`HEALTH_ALL` has been merged. Now just need to update the documentation.

**Comment by jacwah** [comment]
Docs updated c335aa295784067c66496d39ecd0bfd577f23757
