### ISSUE TITLE
`MANA_MAX` and `MAX_HEALTH`

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#390]
The naming of these two resources is inconsistent. #384 is related if we also add `HEALTH_ALL`.

**Comment by Zomis** [comment]
Thanks for bringing this up, this has been bothering me too!

**Comment by jacwah** [comment]
I think `MAX_MANA` and `MAX_HEALTH` is best for the DSL since it's meant to read as English.

`BOTH_HEALTH` conveys more meaning than `HEALTH_ALL` and matches the style above.
