### ISSUE TITLE
Can't release with untracked files

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#399]
$ ./gradlew clean release

    [...]

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':checkCommitNeeded'.
    > You have unversioned files:
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ?? relink
      ?? relink.py
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This might be intentional, but I don't understand why it would be useful. The files are scripts I used [to fix image links](https://github.com/Cardshifter/Cardshifter/commit/9e1df1bd9c413d89008f9a4a18e97d68c6cb3a05) and are not a part of Cardshifter, though I found it useful to keep them in the same directory.

I worked around this by stashing those files before re-running Gradle.

If we decide to not fix this, the wiki on creating a release should be updated to explain this quirk.

**Comment by Zomis** [comment]
I don't think that this should be fixed. Such files should either be removed, be added to `.gitignore`, or be added to the repository. I think this is a completely reasonable alert by the Gradle-release plugin.

For the record, I believe this is configurable, but I don't think we should change the configuration.

**Comment by Zomis** [comment]
Basically what the task seems to do is to check that the working directory is in a clean state, which is a good thing to have before making a release.

**Comment by jacwah** [comment]
I added this as a step to https://github.com/Cardshifter/Cardshifter/wiki/Creating-a-release
