### ISSUE TITLE
Improve readability of effect text

### ISSUE THREAD

**Issue by Lokkij** [Cardshifter/Cardshifter#402]
There are a few areas in which the readability of the effect text can be improved:

- `Choose at random` cards currently list all their possibilities (including duplicates) in plain text which isn't readable at all if there are more than two very simple options. Perhaps the options can be put into a bullet list somehow to improve this.
- The timing of effects is currently displayed after the effect itself (`[effect] at the start of your turn`). To match TCG conventions and improve readability this should be placed before the effect (`At the start of your turn, [effect]`). This also helps the readability of the `choose at random` cards.
- Lastly, I feel like it's important to indicate continuous effects in the card text as well: something like `as long as ~ is on the battlefield, [effect]`.

Thoughts?

**Comment by Lokkij** [comment]
I also just discovered cards with multiple abilities (for example, GAIA from Mythos) need to end their sentences with periods.

**Comment by jacwah** [comment]
* `choose n atRandom` generates descriptions like this: `Choose 1 at random from "Perish", "All players draw 1 card"`.
* Trigger text is displayed first: `At the start of your turn, perish`.
* `whilePresent` effects are described like this: `As long as this is on the battlefield, give this card -1 HEALTH`.
* As for ending sentences with period, does any card currently do that? In any case, it can be done.

What do you think of these changes @Lokkij? Do you still prefer a bullet list over quoted string?

**Comment by Phrancis** [comment]
I think this looks great and we should merge it, if everything works OK. Great work :+1:

**Comment by Lokkij** [comment]
Great work!

I do prefer the bullet list, yes. It's essentially the difference between [this](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370439&type=card) Cryptic Command and [this one](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=397793&type=card).

**Comment by jacwah** [comment]
Now descriptions look like this:
```
Choose 1 at random:
 - Perish
 - All players draw 1 card
```

**Comment by Phrancis** [comment]
This is minor, but I think changing `Choose 1 at random` to `Chooses 1 at random` would be better (since the player doesn't get to do the choosing, rather card's "dice"/"coin flip" does)

**Comment by jacwah** [comment]
@Zomis:
> "Choose 1 at random" works for me. I think that's how MtG has done it.

If we reach a consensus in this I'll change it.

**Comment by jacwah** [comment]
This is now merged. If you still want descriptions to end with period, open a new issue.
