### ISSUE TITLE
Destroy a target card

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#417]
It should be possible to simply destroy a target card with a spell or such. Right now we can get around it doing something like

    spell { targets 1 cards { creature 'true' } }
    afterPlay { damage 9999 to targets }

But that's a bit crazy I'm sure we'll agree. Something like `afterPlay { destroy targets }` would be much more instinctual and better.

**Comment by Zomis** [comment]
With a little trick, we could probably re-use #408 for this. How about this?

    afterPlay {
       to targets perform {
           perish()
       }
    }

**Comment by Phrancis** [comment]
I think that would work. I'm not a huge fan of having more keywords after the closing bracket right now, since we don't have anything else in the DSL with this syntax though.

**Comment by Zomis** [comment]
Note that the "to targets" part could in both examples be replaced with a target-closure, such as:

    afterPlay {
       effect {
           perish()
       } to {
           creatureType 'Greek'
           zone 'Battlefield'
       }
    }

Technically, "targets" *is* a TargetFilter IIRC.

**Comment by jacwah** [comment]
`targets` is an `Object` AFAIK.

These two suggestions are elegant from a programmer's perspective, but I think they run the danger of being too meta for someone not used to programming.
