### ISSUE TITLE
Gender flags for cards?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#422]
I just had a thought, and wanted to see if others thought it would be a good idea for discussion. This would be principally a way to possibly improve UX and personalize cards a bit more. 

This could be used for any number of things including changing the verbiage displayed on cards, to client changes (card colors or any other thing like that). 

Alternatively, perhaps we could just implement generic personality tags and let the modders and client designers decide what they are for?

**Comment by jacwah** [comment]
I'm not sure adding a gender to cards is a good idea. I don't think female and male cards should be colored differently. There's also the possibility of cards that have either no or unknown gender. 

Cards could have a pronoun property for the generated description, right now they're only referred to as "this" and "it".

What other personality tags do you have in mind?

**Comment by Phrancis** [comment]
Yeah I think you're right. It sounded like a good idea at the time but I'm not sure now that this would really serve much purpose. The idea came when I was looking at Mythos cards, one was of type "Hindu God" but the flavor said "Goddess". This is probably too _meta_ to be really useful or desirable.
