### ISSUE TITLE
Move the GDX project

### ISSUE THREAD

**Issue by marcandregirard** [Cardshifter/Cardshifter#437]
We should move the GDX project in it's own repo. It's a separate project that should live on it's own repo.

**Comment by marcandregirard** [comment]
This has been done already, I don't know if it has been merged in dev or main yet. The gdx repo exist on Cardshifter. We can probably close this issue.

**Comment by Zomis** [comment]
The GDX project is not even the recommended client anymore as well. The most actual client is https://github.com/Cardshifter/HTML-Client
