### ISSUE TITLE
Website homepage in README is a 502 gateway error

### ISSUE THREAD

**Issue by ahungry** [Cardshifter/Cardshifter#451]
Website homepage in README is a 502 gateway error

**Comment by Zomis** [comment]
Hi. Unfortunately this project is no longer being worked on and therefore its website is no longer actively maintained either.

I am however planning on bringing the learnings - and hopefully also the current game implementations - from this project onto this project: https://github.com/Zomis/Games . If you are interested in what this project does, the Zomis/Games project might interest you as well.
