### ISSUE TITLE
Add new attributes to cards

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#53]
Please add the following attributes for cards:

- An actual ID field
- Card name
- Card description

I will leave the naming of those fields to developers' discretion.

**Comment by Zomis** [comment]
Names has been added and showing properly, descriptions are not showing correctly yet though. (Neither flavortext, nor actual descriptions about what the effects are)

**Comment by Zomis** [comment]
Effect descriptions has now been added to LibGDX. Only JavaFX remaining, but that I won't take care of now.

**Comment by Zomis** [comment]
It's not implemented in a very clean way in JavaFX, I am giving priority to LibGDX implementation instead. JavaFX can/should be refactored later,  see #57
