### ISSUE TITLE
How to use TCG?

### ISSUE THREAD

**Issue by janosgyerik** [Cardshifter/Cardshifter#55]
It would be good to add in the README how to use TCG.
Doing so could draw more interested coders to the project.
Without a good description at the front, it's hard to feel compelled to dig into the code to find out.

I know it's a young project. It's normal that it's in a flux and probably even fundamental things can change, which could make it difficult to write a proper overview. But at least a brief summary of the core ideas to spark interest in visitors would be good, and definitely better than nothing.

**Comment by Phrancis** [comment]
@Zomis I noticed this one In Progress. Rules were updated on [#142](https://github.com/Cardshifter/Cardshifter/issues/142) and a good portion of the game is explained on the website now. Shall we close this?

**Comment by Zomis** [comment]
@Phrancis No, this is about updating the README.md for the repository. It should be less about developer guidelines and more about wwhat this project *is*.

**Comment by Phrancis** [comment]
Created branch `repo-documentation` for this purpose. Will move developed guidelines to wiki and leave a link to there (and other pages) on the README.md.

**Comment by Phrancis** [comment]
[Changes committed](https://github.com/Cardshifter/Cardshifter/commit/92f6f16e096ff724ac3c90992fb970e251ffad7d) and awaiting peer review to see if any other changes are desired.

**Comment by Phrancis** [comment]
[Tentatively final commit](https://github.com/Cardshifter/Cardshifter/commit/2f6aa9097ee051038df315c02bd3ed66be8efca6) for 0.4 awaiting peer approval.

**Comment by Phrancis** [comment]
Done, just need merged into the relevant branch(es).
