### ISSUE TITLE
Refactor Cardshifter-FX

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#57]
The cardshifter-fx module needs some refactoring to reduce code duplication and improve flexibility. This mainly applies to the client that connects to the server as that client is more important, but the stand-alone GUI can be refactored as well.

**Comment by Phrancis** [comment]
Are we planning to keep supporting both JavaFX and libGDX for a good while still? Or should we shoot to move everything to libGDX perhaps for 0.7 / 0.8?

**Comment by Zomis** [comment]
Honestly, I don't know. I am not convinced that LibGDX is the best option to go with either. It depends a lot on what platforms we want to aim at. If we aim at iOS, HTML 5, *and* Android, then LibGDX is probably the best option (or one of the best options). LibGDX development is a bit complicated though. But I think we should at least maintain some support for JavaFX as well.

**Comment by Zomis** [comment]
Who cares about Cardshifter-FX? We've got a HTML Client in Vue.

**Comment by Phrancis** [comment]
Agreed. I only ever use the FX client for debugging/testing purposes, I think it's fine to abandon any further development on it.
