### ISSUE TITLE
Effects / Abilities

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/Cardshifter#74]
Cards should be able to do more than just be creatures and attack, or enchanting creatures. **Add support** for *spells* and triggers such as "At the end of your turn, give a minion +2 health" / "Whenever one of your Bio creatures attack, draw a card" / "Give a minion the ability to attack twice each turn". (etc, etc.)

**Comment by Phrancis** [comment]
Here are the 5 card effects the game designers would like to integrate at first:
- Ranged. Suffers no damage when attacking.
- Rush. No cast sickness.
- Cannot attack.
- Heals the player for 1 health at the end of each turn
- Cannot attack. Cast 2 Bodyman minions at no cost next to this unit.

The list of cards to which those effects will be applied can be found at the following link: https://github.com/Cardshifter/Cardshifter/blob/database/cardshifter-database/excel_files/TCG%20card%20list%2010-28-14.xlsx

**Comment by Zomis** [comment]
@Phrancis I cannot find any cards in the Excel file that has these card effects. I only find the following effects in the excel file, which should be applied to 8 different spells:

Opponent cannot scrap Mechs next turn.
Opponent cannot play Bios next turn.
Opponent cannot play any Upgrade next turn.
Deal 2 damage to all Mechs.
Owned Mechs gain 2 Attack this turn only.
Owned Mechs gain 2 Health during next opponent turn.
Restore 3 health to the player.
Restore 10 health to the player.

I am not able to find any creatures with the abilities you mentioned (Ranged, Cannot attack, etc...)

**Comment by Phrancis** [comment]
Sorry my file is a bit confusing to read. I'm not sure we should integrate cards of type Spell or Hume just yet, but of the creatures themselves, here are those with the effects listed:

• Ranged. Suffers no damage when attacking - Gyrodroid (Mech), Assasinatrix (Mech), Longshot (Bio), Cybernetic Arm Cannon (Upgrade)
• Rush. No cast sickness - Scout Mech, Modleg Ambusher (Mech), Commander (Bio), Adrenalin Injection (Upgrade)
• Cannot attack - Supply Mech
• Heals the player for 1 health at the end of each turn - Field Medic (Bio)
• Cannot attack. Cast 2 Bodyman minions at no cost next to this unit - Inside Man (Bio)

**Comment by Zomis** [comment]
The above functionality has been implemented. Closing this issue, as essentially - it works. Adding new features is not too hard either (at least not for me who knows how the ECS stuff works)
